### ISSUE TITLE
Update funding section: Mention Shipyard

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#1103]
As part of the dev docs, I think a page on Ocean running programs can help onboarding community members.
* DAO that is available for retroactive funding
* Shipyard for project proposals with a larger funding cap
* Ventures

I know we have this information available all over the places via blogposts, site, tweets, and so on but I think a page to briefly describe the programs and the mechanisms could be useful. 

We can use these blog posts:
* https://blog.oceanprotocol.com/introducing-oceandao-efe9ed681b84
* https://blog.oceanprotocol.com/ocean-shipyard-first-wave-january-2020-ac0f8f80e23c-ac0f8f80e23c
* https://blog.oceanprotocol.com/a-new-grantee-is-joining-shipyard-brainstem-digital-health-bfa478b3566b

**Comment by AnaLoznianu** [comment]
@akshay-ap @jamiehewitt15 @mihaisc What do you think?

**Comment by mihaisc** [comment]
Not necessarily a bad idea but it's more of a marketing thing. Not sure how this is helpful for someone coming to the docs. This is more of a site thing.

**Comment by jamiehewitt15** [comment]
I think it's good to send people to the main site to get more details so that we don't have to keep updating both places. That's what we've done currently for the [funding section](https://docs.oceanprotocol.com/building-with-ocean/contributing#get-funding). I think a good place to start would be to adapt that section so that it has links to both the DAO page and the shipyard page, with a couple of sentences to explain the difference.  

As far as I can see there is nothing on the main site about Ocean Ventures at the moment?

**Comment by akshay-ap** [comment]
> 

I second this. I think this content will get better visibility if its on main site (accessed even by non-devs) rather than docs.

**Comment by jamiehewitt15** [comment]
Ok, so conclusion on this is to do an update to the [funding section](https://docs.oceanprotocol.com/building-with-ocean/contributing#get-funding) so that we are also linking to shipyard. For now at least there is no need for a whole page to be dedicated to funding within the docs.
