### ISSUE TITLE
Update the OceanAsset.create() call in the React app tutorial

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/docs#252]
`OceanAsset.create()` now takes three arguments:

https://docs.oceanprotocol.com/references/squid-js/#OceanAssets-create

1. metadata `MetaData`
1. publisher `Account`
1. services `Service[]`

but the React App Tutorial currently only calls it with the first two arguments, see:

https://docs.oceanprotocol.com/tutorials/react-publish-data-set/#handle-asset-publishing

**Comment by kremalicious** [comment]
good find, in commons & pleuston we call it with 2 arguments only and this seems to work regardless.

It works, because a default is set for `services` here https://github.com/oceanprotocol/squid-js/blob/develop/src/ddo/Service.ts#L4

So I think unless you want to change that, providing the 3rd argument is not required.

**Comment by ttmc** [comment]
I guess if the third argument is not required, then this is a non-issue and it can be closed.
