### ISSUE TITLE
Ocean.js and Ocean.py tutorials

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/docs#782]
**Is your feature request related to a problem? Please describe.**
We have a dedicated `Turorials` page in docs: https://docs.oceanprotocol.com/tutorials/introduction/.
But, the docs doc not mention anything about ocean.py or ocean.js. We have the tutorials for ocean.py in pymodules [here](https://docs.oceanprotocol.com/references/read-the-docs/ocean-py/READMEs/datatokens-flow.md) but, I think a better place would also be tutorials page.

- We should not repeat the tutorials by copying them as it will create a maintainence overhead.
- It would be great if we setup some flow in docs so that tutorials from ocean.py and ocean.js are fetched and renderd in Tutorials page.
- We do not remove any docs from py modules.

**Describe the solution you'd like**
A section for ocean.py and oceanjs tutorials in Tutorials page sourced from READMEs.

**Comment by trentmc** [comment]
What does this accomplish that the readmes do not? I worry about overlap.

**Comment by akshay-ap** [comment]
@trentmc, I have updated the issue discription. Issue was created initially just as a place holder.

**Comment by trentmc** [comment]
> I have updated the issue description. Issue was created initially just as a placeholder.

Thanks for the update. I like the description now. +1

**Comment by kremalicious** [comment]
This splitup of our SDK in different tutorials does not make sense. What users want is one tutorial with different code examples for the same flow. Cause the basic flows are simply the same. And for us we do not need to duplicate everything.

Since this would take some time to me the most practical solution is to write tutorials which default to ocean.js examples. And only deal with ocean.py in some dedicated datascience tutorial. All Dapp developers building market places use ocean.js so that should have highest priority

**Comment by trentmc** [comment]
> All Dapp developers building market places use ocean.js so that should have highest priority,

And all data scientists will use ocean.py. 99% of AI/ML/data science is done in python. They are key users too.

I'm making the following point: I see the use cases for ocean.js and ocean.py diverging quite a lot. Things like the C2D README in ocean.py won't really have an equivalent in ocean.js. 

And this is ok!

I propose that both ocean.js and ocean.py have the same _basic_ tutorial or README info (eg datatokens quickstart, market quickstart). And beyond that let their tutorials/READMEs evolve according to their target audiences.
