### ISSUE TITLE
Document Opensea integration

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/docs#996]
**Is your feature request related to a problem? Please describe.**
Add few lines explaining how our NFTs are integrated into Opensea. It might be worth to open a discussion about it, as it involves high level of knowledge of how ocean works.

Some questions that I have in mind are:

1. Why did we choice Opensea over other marketplaces?
2. What can we do on Opensea and our DataNFT?
3. Can we action, sell, buy them on Opensea?
4. How is ownership being handle in the case of selling on Opensea?
...

Probably we can add some more, as well as reminding everybody that in order to be see all the metadata correctly on Opensea they need to refresh it with the dedicated button.

**Comment by trentmc** [comment]
Here are some answers

1. We didn't choose Opensea over other marketplaces. We simply made sure that ERC721 metadata format _also_ followed Opensea's metadata standards. Why? Because it has been the largest NFT marketplace, and it's become standard practice for NFT projects to follow its standards
2. Buy, sell, etc data NFTs just like any other NFT on Opensea
3. See 2
4. Just like any other NFT on Opensea. (This could probably be fleshed out more)

**Comment by akshay-ap** [comment]
Mention in dataNFT and datatoken page that dataNFT follows ERC721 standard so it can be used with other services supporting ERC721 .e.g. opensea

**Comment by AnaLoznianu** [comment]
Done in V2 Docs.
