### ISSUE TITLE
V4 docs are pointing to V3 components 

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/docs#998]
When a new release is out, the V4 docs picks it up and points to it. It doesn't matter that the release is a V3 or a V4 one.
We need a way to separate these two and have clear rules for updating the docs with a new release

An example is the provider. A new V3 version was pushed and the V4 docs are pointing to it. 
The same could go for each component
<img width="1233" alt="Screenshot 2022-05-19 at 09 37 35" src="https://user-images.githubusercontent.com/84312885/169226463-78241c99-f23f-4f18-aed6-f6564eca6e6a.png">

**Comment by akshay-ap** [comment]
This happened because we had releases for v3 components after v4. Docs simply pick the latest release irrespective of the version v3/v4. 
Now, there are new releases for v4 components after v3 patches and docs site point to latest versions of v4.

![image](https://user-images.githubusercontent.com/16358982/171489989-fd310296-64e8-4842-95d8-8d479b46a49b.png)


@AnaLoznianu this problem can reoccur only if we have a release for any of v3 component in future. If there is no plan to do any v3 release henceforth there will be no problem.
